# NOTE: This code has been automatically generated by desilike.bindings.cobaya.factory.CobayaLikelihoodGenerator
from desilike.bindings.cobaya.factory import CobayaLikelihoodFactory

# CGQ: BAO likelihood
from bao_desilike import CompressedBAOLikelihood
CompressedBAOLikelihood = CobayaLikelihoodFactory(CompressedBAOLikelihood, 'CompressedBAOLikelihood', {'cosmo': 'external'}, __name__)

# CGQ: BAO/RSD likelihood
from bao_desilike import CompressedBAORSDLikelihood
CompressedBAORSDLikelihood = CobayaLikelihoodFactory(CompressedBAORSDLikelihood, 'CompressedBAORSDLikelihood', {'cosmo': 'external'}, __name__)

